apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: f7c8cd00-206f-4177-85d0-6690caae14d8
  creationTimestamp: null
  name: echo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: echo
  strategy:
    canary:
      canaryService: echo-canary
      stableService: echo
      steps:
      - setWeight: 10
      - pause:
          duration: 180
      - setWeight: 20
      - pause:
          duration: 180
      - setWeight: 30
      - pause:
          duration: 180
      - setWeight: 40
      - pause:
          duration: 180
      - setWeight: 50
      - pause:
          duration: 180
      - setWeight: 60
      - pause:
          duration: 180
      - setWeight: 70
      - pause:
          duration: 180
      - setWeight: 80
      - pause:
          duration: 180
      - setWeight: 90
      - pause:
          duration: 180
      - setWeight: 100
      - pause:
          duration: 180
      trafficRouting:
        ambassador:
          mappings:
          - echo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - args:
        - -text=Successful Argo deployment!
        - -listen=:8080
        image: hashicorp/http-echo:latest
        imagePullPolicy: Always
        name: echo
        ports:
        - containerPort: 8080
        resources: {}
status:
  blueGreen: {}
  canary: {}
