apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 80035b56-d718-441d-ac72-3d468c31ab6d
  creationTimestamp: null
  name: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  strategy:
    canary:
      canaryService: echo-canary
      stableService: echo
      steps:
      - setWeight: 50
      - pause:
          duration: 30
      - setWeight: 100
      - pause:
          duration: 30
      trafficRouting:
        ambassador:
          mappings:
          - echo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - args:
        - -text=Successful Argo deployment!
        - -listen=:8080
        image: hashicorp/http-echo:latest
        imagePullPolicy: Always
        name: echo
        ports:
        - containerPort: 8080
        resources: {}
status:
  blueGreen: {}
  canary: {}
