apiVersion: v1
kind: Service
metadata:
  annotations:
    a8r.io/description: "Echo Service"
    a8r.io/owner: "cakuros@github.com"
    a8r.io/chat: "a84.io/slack"
    a8r.io/bugs: "https://github.com/aes-t2/sol-eng-argo-qs/issues"
    a8r.io/logs: "https://github.com/aes-t2/sol-eng-argo-qs/issues"
    a8r.io/documentation: "https://github.com/aes-t2/sol-eng-argo-qs/issues"
    a8r.io/repository: "https://github.com/aes-t2/sol-eng-argo-qs"
    a8r.io/support: "https://github.com/aes-t2/sol-eng-argo-qs/issues"
    a8r.io/runbook: "https://github.com/aes-t2/sol-eng-argo-qs/issues"
    a8r.io/incidents: "https://github.com/aes-t2/sol-eng-argo-qs/issues"
    a8r.io/uptime: "https://linkerd.amb-labs.io/namespaces/default"
    a8r.io/performance: "https://linkerd.amb-labs.io/namespaces/default"
    a8r.io/rollouts.scm.branch: "main"
    a8r.io/rollouts.scm.path: "echo"
    a8r.io/rollouts.image-repo.type: "dockerhub"
    a8r.io/rollouts.image-repo.name: "hashicorp/http-echo"
    a8r.io/rollouts.deployment: "echo"
    a8r.io/rollouts.mappings: "echo"
  labels:
    app: echo
  name: echo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
