apiVersion: v1
kind: Service
metadata:
  annotations:
    a8r.io/description: "A simple echo service for testing Argo Rollouts"
    a8r.io/owner: cakuros@github.com
    a8r.io/chat: a8r.io/slack
    a8r.io/bugs: https://github.com/aes-t2/sol-eng-argo-qs/issues
    a8r.io/logs: https://github.com/aes-t2/sol-eng-argo-qs/issues
    a8r.io/documentation: https://github.com/aes-t2/sol-eng-argo-qs/issues
    a8r.io/repository: https://github.com/aes-t2/sol-eng-argo-qs
    a8r.io/support: https://github.com/aes-t2/sol-eng-argo-qs/issues
    a8r.io/runbook: https://github.com/aes-t2/sol-eng-argo-qs/issues
    a8r.io/incidents: https://github.com/aes-t2/sol-eng-argo-qs/issues
    a8r.io/uptime: https://github.com/aes-t2/sol-eng-argo-qs/issues
    a8r.io/performance: https://github.com/aes-t2/sol-eng-argo-qs/issues
  labels:
    app: echo
  name: echo-stable
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo-canary
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo 
